# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export ZSH="${HOME}/.oh-my-zsh"
export GOPATH=$HOME
export GO111MODULE=on
export GOPRIVATE="github.com/Shopify/*"

export PATH="$HOME/.bin:$PATH"
export PATH=/usr/local/bin:$PATH
export PATH="$GOPATH/bin:$PATH"
export PATH="${PATH}:${HOME}/.krew/bin"
export PATH="${PATH}:${HOME}/.npm-global/bin"
export PATH="${PATH}:/usr/local/go/bin"

# recommended by brew doctor
export PATH="/usr/local/bin:$PATH"

export EDITOR=vim
export DOCKER_BUILDKIT=1

# shellcheck disable=SC2034
ZSH_THEME="powerlevel10k/powerlevel10k"
export UPDATE_ZSH_DAYS=5

# shellcheck disable=SC2034
plugins=(
  autoupdate
  colorize
  colored-man-pages
  docker
  fast-syntax-highlighting
  git
  history-substring-search
  vscode
  you-should-use
  zsh-autosuggestions
)

# shellcheck disable=SC1090
source $ZSH/oh-my-zsh.sh

# Import Aliases
if [ -f ~/.aliases ]; then
  source ~/.aliases
else
  print "404: ~/.aliases not found."
fi

# Source
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

# update prompt to show k8s info
source ${HOME}/.kube_ps1/kube-ps1.sh
PROMPT='$(kube_ps1)'$PROMPT
KUBE_PS1_SYMBOL_ENABLE=false # disable k8s icon

# shellcheck disable=SC1091
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc';
fi

# shellcheck disable=SC1091
if [ -f '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc' ]; then
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc';
fi

# cloudplatform: add Shopify clusters to your local kubernetes config
export KUBECONFIG="${HOME}/.kube/config"

for file in $HOME/src/github.com/karanthukral/dotify/dotfiles/*.bash; do source ${file}; done
kubectl-short-aliases

autoload -U +X bashcompinit && bashcompinit

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(direnv hook zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
